### ISSUE TITLE
Missing curtain

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#11]
The two half sized windows to the right of the emergency exit are missing a curtain. This tends to be problematic due to the projection screen beeing unevenly lit by background light form the street light outside. Also when blacking out the Hubben one has to tape garbage bags on those windows instead of using a simple curtain.

**Comment by Tejpbit** [comment]
We have discussed new blackout curtains over all of the windows, nothing serious but we'll duscuss it further during our next meeting on monday.

**Comment by JonatanGust** [comment]
The new blinds installed by P.R.I.T. 16 fixes this problem.
