### ISSUE TITLE
Days since issue screen

### ISSUE THREAD

**Issue by Kalior** [cthit/Hubben#15]
Hubben needs a days since issue screen that shows the amount of days since an issue was last reported

**Comment by Edholm** [comment]
Also, [accidents!](https://i.ytimg.com/vi/hfzbB_B3HS0/hqdefault.jpg)

**Comment by lindskogen** [comment]
@Edholm exactly what I was thinking about!

**Comment by Tejpbit** [comment]
Sounds like something digIT should implement on the info-screen

**Comment by Tejpbit** [comment]
Issue added to tv-repository
https://github.com/cthit/tv/issues/6
