### ISSUE TITLE
Get a longer optical cable to the sound system

### ISSUE THREAD

**Issue by Kalior** [cthit/Hubben#19]
The current cable seems to be too short to have it drawn along the ceiling. A new cable needs to be bought and then have it go along the ceiling.

**Comment by Tejpbit** [comment]
We'll check the costs and if it's reasonable we'll buy a cable and let someone set it up during the next fix the Hubb day ("fixahubbendagen".)

**Comment by Kalior** [comment]
@Kerp1 estimated the length of the cable to have to be about 16 meters so maybe a 20 meter cable?

**Comment by Kerp1** [comment]
Also if you're buying this, buy 4m Cableduct that can fit the cable for the wall next to the loudspeaker.
