### ISSUE TITLE
Larger garbage stations.

### ISSUE THREAD

**Issue by Kalior** [cthit/Hubben#24]
Especially a larger cardboard drawer in the garbage station in the kitchen. The current size does not even fit all of digITs pizzaboxes every Tuesday, this is a problem.

**Comment by oherik** [comment]
We've contacted Akademiska Hus regarding this, and are waiting for their reply.

**Comment by ClausX** [comment]
Akademiska Hus doesn't seem to be interested in changing the garbage stations.
