### ISSUE TITLE
Fix coffee machine

### ISSUE THREAD

**Issue by Kerp1** [cthit/Hubben#3]
The placement of the coffee machine is unbearable. It needs to be moved to a place where we can reach it without stretching. We also don't want to accidentally pour water into the power outlet.

**Comment by Tejpbit** [comment]
That was the plan all along. We just need to get our thumb out of our asses and move it.

**Comment by Edholm** [comment]
Tejps ass: ```    (_!_)```
Tejps thumb: :+1:
