### ISSUE TITLE
Whiteboard in the grouproom

### ISSUE THREAD

**Issue by Kerp1** [cthit/Hubben#30]
Since fixa hubben dagen it's impossible to get the whiteboard clean. I suggest you clean it with the recommended cleaning solution  and then buy new erasers.

**Comment by Tejpbit** [comment]
Note to self can buy at http://www.clasohlson.com/se search for "whiteboard"

**Comment by Tejpbit** [comment]
New whiteboard tools bought. We'll see how it do. Closing issue for now
