### ISSUE TITLE
Coffee-shelf might break soon

### ISSUE THREAD

**Issue by Fredokin** [cthit/Hubben#32]
Kolla på hyllan där kaffebryggaren står: den buktar ner på mitten, troligtvis pga fuktskada. Värt att hålla ett öga på / fixa

**Comment by Tejpbit** [comment]
Japp, värt att köpa ny hylla och behandla den med någon fuktfrånstötande. Vilket också kommer göra den lättare att tvätta av från allt spillt kaffe.

**Comment by vidare** [comment]
Vaxduk is the way to go.

**Comment by oherik** [comment]
Ny hylla inköpt, vaxduk fastspikad på den. Hyllan uppsatt.
