### ISSUE TITLE
Bubble in one of the tables in hubben 

### ISSUE THREAD

**Issue by Kalior** [cthit/Hubben#34]
The table to the right when looking away from the bar when at the bar to the right

**Comment by oherik** [comment]
Bubble? Is it wobbly or is there some damage to the table itself? I'll have a look at it, but the tables have been rearranged during the weekend (ET-raj cleaning).

**Comment by Kalior** [comment]
There seems to be some damage to the table, although I did not investigate
further.

**Comment by oherik** [comment]
Temporarily fixed using cardboard.

**Comment by oherik** [comment]
Permanently fixed
