### ISSUE TITLE
Loose element in the hub 

### ISSUE THREAD

**Issue by Kerp1** [cthit/Hubben#35]
The radiator next to the emergency exit in the main area of the hub is not attached to the wall very good.

**Comment by oherik** [comment]
Roger that. I'll have a look at it, but it's probably a job for the
groundkeeper  or Akademiska hus. If that's the case, I'll see to it that
they're notified.

**Comment by oherik** [comment]
We have contacted the groundskeeper regarding this.

**Comment by ClausX** [comment]
This has been fixed
