### ISSUE TITLE
Clocks

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#36]
To my knowledge the only (working) clock is located in the kitchen. At least one in the Studierum should be useful, there may also be a need for a clock in different location in Hubben. An analogue clock is cheap so there should be no problem buying a couple.

**Comment by oherik** [comment]
Since clocks are allowed in Hubben as of 2007, I'll bring it up with the others.

**Comment by oherik** [comment]
We have decided that three clocks will be bought and installed: one in the main area, one in the study room and one in the group room.

**Comment by lindskogen** [comment]
Feature suggestion: Radio controlled clocks!

**Comment by Hultner** [comment]
I for one support the olden ways where clocks were strictly forbidden in the Hub and don't think PRIT should encourage the use of such a controversial piece of equipment.

**Comment by oherik** [comment]
Clocks have been put up on the walls of the main room, the study room and the group room.
