### ISSUE TITLE
No coke in Hubben

### ISSUE THREAD

**Issue by lindskogen** [cthit/Hubben#37]
We want coke in Hubben! 
We cannot code without coke!

**Comment by Edholm** [comment]
@lindskogen [Is this your?](http://imgur.com/7lsKiWK)

**Comment by lindskogen** [comment]
Vending machine is out again!

**Comment by ClausX** [comment]
Right, i've tried calling the vending machine guy, but he didn't answer. Will contact him again.

**Comment by ClausX** [comment]
I've talked with the guy and he should try more Coke next time. Issue closed.
