### ISSUE TITLE
Photo of Nollan in the study room

### ISSUE THREAD

**Issue by Kerp1** [cthit/Hubben#38]
There are several photos of Nollan missing from the wall in the studyroom, at least since 2013 but maybe some more.

**Comment by Dr-Horv** [comment]
I talked with the President of CFFC. Should be no problem of finding the old photos in their achieve. So pop 'em a mail and they'll sort it out. @oherik

**Comment by oherik** [comment]
We're going to look into this when we get back from the break/re-exams!

2016-03-22 23:28 GMT+01:00 Johan Andersson <notifications@github.com>:

**Comment by Dr-Horv** [comment]
@oherik How's it going?

**Comment by ClausX** [comment]
We have ordered the missing photos, waiting for the to arrive

**Comment by anembac** [comment]
This was fixed on the last "Fixa-Hubben-Dagen".
