### ISSUE TITLE
Left channel on audio cable is bork

### ISSUE THREAD

**Issue by m0ar** [cthit/Hubben#46]
The amplifier only shows activity on the right channel, either the cable or the amp is broken.

**Comment by oed** [comment]
Investigations by kruken has shown that it is the amp that is broken. Switching between different inputs on the amp yeilds the same results.

**Comment by lindskogen** [comment]
:cry:

**Comment by oherik** [comment]
Well... Anybody got a spare amp?

**Comment by m0ar** [comment]
Actually, GasqueK might have a beastly Yamaha laying around. It drove parts
of the dance floor earlier so it should suffice for the group room.

**Comment by Edholm** [comment]
I've temporarily solved the problem by connecting both speakers to the right channel. Works fine!

**Comment by oed** [comment]
That's not a solution, thats an ugly hack!

**Comment by Edholm** [comment]
@oed hence the "temporarily" :+1:

**Comment by ghost** [comment]
The amp was replaced some time back :)
