### ISSUE TITLE
Name of the beverage refrigerator

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/Hubben#48]
While a new refrigerator may warren a new name, I personally am not fond of the new name. The old "Ligga?" felt to be in student spirit and with good associations. This new "TVÅAN" especially with the added "Smaken är som baken" has, at least for me, very mixed associations and feelings. 

If I'm alone with not liking the new name it isn't that big of a deal. I don't demand a change but I've heard other division members say similar things and I'd like to raise the issue for discussion.

**Comment by NeonNeon** [comment]
I do not like the new name either, maybe P.R.I.T. can have some sort of competition and let members of the IT division submit suggestions of names. At least I believe it should be changed before the new nollan arrives this september.
+1

**Comment by oherik** [comment]
Honestly, we in P.R.I.T. didn't choose the name, nor did we make the sign.
Our original name was Ligga mer?, but the sign was replaced by a group of
students. We'll look into maybe changing the name.

**Comment by Solisol** [comment]
Why not have something a bit more related such as "Öl är gott" in some fancy font?

**Comment by abjugard** [comment]
I agree, "Ligga mer?" was much better. The current name is not especially funny in my opinion.

**Comment by Edholm** [comment]
Since the last fridge was smaller and thus any beverages would have to "ligga" to fit, the new fridge should be named "Stå" since it is larger!

**Comment by oed** [comment]
We could just name it "kyl" since that is the most accurate description of its function.

**Comment by Rawa** [comment]
I'm gonna say something insane. How about just sticking with the old name "Ligga?", just because the refrigerator have been replaced doesn't mean we have to give it a new name, right? As Horv mentioned the name "Ligga?" felt to be in student spirit and with good associations.

**Comment by Dr-Horv** [comment]
I for one liked the PRIT spin on it with adding "MER" to it. So it was "Ligga MER" with corresponding art.

**Comment by JonatanGust** [comment]
Name has been "Ligga MER" for atleast half a year now, it seems this name is good enough.
