### ISSUE TITLE
Pizza box recycling container

### ISSUE THREAD

**Issue by abjugard** [cthit/Hubben#50]
The addition of a pizza box recycling container to Hubben would be very useful. A lot of students eat pizza in Hubben and, besides the positive environmental aspect of recycling the boxes, the rubbish bins fill up quite quickly when you stuff a couple of pizza boxes in them.

I'm thinking of something similar to the single use grill recycling that is used in, for example, Slottskogen.

**Comment by oherik** [comment]
We've discussed this during today's meeting. We feel that, while it would
be nice to have a dedicated pizza container, that it would bee to much of a
hassle making sure that it is emptied regularly. However, we've asked
Akademiska Hus to provide larger bins for cardboard, so hopefully that will
take care of most of the issue.

2016-05-17 17:53 GMT+02:00 Adrian Bjugård <notifications@github.com>:
