### ISSUE TITLE
Marker pen and knife hanging from the fridge

### ISSUE THREAD

**Issue by Kalior** [cthit/Hubben#53]
Wouldn't it be great if, as well as having a knife hanging from the fridge:
![img_20160906_091438](https://cloud.githubusercontent.com/assets/2412457/18264999/bebd98c6-7413-11e6-9295-7de3354c563e.jpg)
we had a marker pen there. Would be great for writing your name on the food.

**Comment by lindskogen** [comment]
The knife is for opening the fridge

**Comment by Dr-Horv** [comment]
Why not both?

**Comment by Kalior** [comment]
Sure, both then. Wasn't aware the knife had a purpose

**Comment by oherik** [comment]
Unfortunately we strongly believe that a pen would be stolen within microseconds. We advise you to bring your own pens or mark your food beforehand.
