### ISSUE TITLE
Air outlet for the small refrigerators behind the bar

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#54]
If the bench above the refrigerator is pushed against the wall no hot air can escape and the cooling becomes minimal. An easy solution to prevent this from happening wold be to put some wooden blocks or a long board behind the legs of the bench against the wall.

**Comment by oherik** [comment]
We do have some spare wood we probably could use for this purpose. I'll look into it the coming week.

**Comment by oherik** [comment]
Fixed using a couple of 45x45mm beams.
