### ISSUE TITLE
Power splitter for the two tables closest to the projector

### ISSUE THREAD

**Issue by Dr-Horv** [cthit/Hubben#55]
The placement of the power outlets for the two tables closest to the projector are a bit awkwardly placed. A suggestion is to place power splitter-cables from the outlets along the wall up on the speaker boxes, easier available for the people and doesn't need to cross the couches.

**Comment by oherik** [comment]
Nice idea. We'll try to get some money for additional power-spliters.

**Comment by fantomsol** [comment]
This is solved now, the power cables in place are borrowed from digIT :)
