### ISSUE TITLE
Additional knife magnet in kitchen

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#56]
Since the trial period for the knife magnet is conclude successfully I propose we buy an additional one. The only problem now is that there are too many knives and only a single magnet. This would also prevent some blunting due to overstacking of the magnet.

**Comment by oherik** [comment]
We will see if there's enough space for an additional one, and if there is, if we can acquire a new magnet.

**Comment by ericlp** [comment]
An additional magnet has now been added to the kitchen.
