### ISSUE TITLE
Window fittings for air intake to Studierummet

### ISSUE THREAD

**Issue by hjorthjort** [cthit/Hubben#58]
Buy one of [these](http://www.clasohlson.com/se/V%C3%A4dringsbeslag/21-2439) and mount on the window in studierummet. The problem of letting air in without the window swinging open, shutting, or hitting someone in the face is persistent. #thestruggleisreal

**Comment by oherik** [comment]
We spoke to the caretaker regarding this a while ago, and he said he would fix it. We'll remind him.
