### ISSUE TITLE
New ladder

### ISSUE THREAD

**Issue by Kerp1** [cthit/Hubben#6]
The ladder right now is very dangerous and is not easy to use.

**Comment by Edholm** [comment]
I think a new ladder has been purchased? Maybe @Tejpbit can enlighten us?

**Comment by Tejpbit** [comment]
Yepp working on it. Still looking for the right one though...

**Comment by Tejpbit** [comment]
No longer working on it. I am no longer P.R.I.T. :)
P.R.I.T.16 will have to discuss this.

**Comment by fantomsol** [comment]
New ladder is bought. It is amazing :)
