### ISSUE TITLE
Put up a sign on the door out of Hubben reminding people to close the windows.

### ISSUE THREAD

**Issue by Tejpbit** [cthit/Hubben#61]
"Är du bland de sista i hubben? Glöm inte att stänga fönstren!" Eller nått sånt. Och någon fin bild på ett fönster, jag föreslår:

 
![image](https://cloud.githubusercontent.com/assets/6124487/21021038/30c1f4d8-bd77-11e6-85d1-ff5b3343484c.png)

**Comment by ClausX** [comment]
juppjupp!
