### ISSUE TITLE
Projector external HDMI cable to short

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#63]
The external HDMI cable for the projector is about 1m to short to be able to connect to a computer located behind the bar counter. Since the new shelves above the bar counter was built the old cable laying is not sufficient anymore, especially for a computer with HDMI port on the far off side. It is possible to connect a computer (regardless of port placement) if it is placed on top of the bar counter, this is not preferred since it will be prone to "damage" from customers and is cumbersome to reach.

**Comment by JonatanGust** [comment]
Good find, work is in progress!

**Comment by Yeetii** [comment]
Solved by Lumo
