### ISSUE TITLE
Chairs are overflowing in Grupprummet

### ISSUE THREAD

**Issue by Holmus** [cthit/Hubben#64]
Could we please get rid of all the #¤%#¤ing extra chairs in grupprummet?

It is impossible to utilize them all at the same time and they end up being obstacles to anyone trying to transport themselves within the room.

**Comment by Kalior** [comment]
Possibly by getting rid of the broken/uncomfortable ones?

**Comment by fantomsol** [comment]
I moved out a few chairs about one or two months ago. It is still quite cramped but better I think?
