### ISSUE TITLE
Better tea in Hubben

### ISSUE THREAD

**Issue by Kalior** [cthit/Hubben#65]
I realise this might not be possible, economy wise, and buy-in wise. But wouldn't it be tremendous if we replaced the boring tea-bags in Hubben with loose leaf tea and [these](http://www.tecentralen.se/tepasar-att-fylla-sjalv.html) kinds of bags. Just my two-cents.

**Comment by JonatanGust** [comment]
P.R.I.T. will look into it. Loose tea is generally much cheaper, but it might also deteriorate faster due to people handling it wrong. However, those type of bags are usually pretty expensive.

**Comment by Yeetii** [comment]
We tried out loose tea and it worked out so we'll be getting more of it. Thank you for the idea!

**Comment by Kalior** [comment]
You guys are the best! #bestP.R.I.T.confirmed :1st_place_medal: :smiley:
