### ISSUE TITLE
liquid determination

### ISSUE THREAD

**Issue by felixjansson** [cthit/Hubben#66]
Hubben needs a new liquid determination carrier though the old one has disappeared?  👽

**Comment by JonatanGust** [comment]
We will look into it

**Comment by SSundstrom** [comment]
[Dunk](https://www.bauhaus.se/vattendunk-25-l.html)
Med
[Tap 10mm](https://www.bauhaus.se/hane-10mm.html)
Eller
[Tap 20mm](https://www.bauhaus.se/hane-20mm.html)
Lös 🔨
