### ISSUE TITLE
Dörrjäveln gnisslar

### ISSUE THREAD

**Issue by hedmanw** [cthit/Hubben#67]
The dörrjävel to the grupprum is the gnissel.
Please use some rapsolja asap.

(The SAMO has also started gnisseling, but perhaps that is an unrelated issue.)

**Comment by Xiaoming94** [comment]
@BalooCTH  Can you have a look at this? I believe this is a P.R.I.T. business 😄

**Comment by abjugard** [comment]
@Xiaoming94 And this repo is for P.R.I.T. so that makes sense.
