### ISSUE TITLE
Fix the refridgerator 'ligga'

### ISSUE THREAD

**Issue by Kerp1** [cthit/Hubben#7]
It doesn't work, when you plug it in it sound awful.

**Comment by lindskogen** [comment]
Still?

**Comment by Dr-Horv** [comment]
Problem reoccured.

**Comment by Edholm** [comment]
The problem is the bearings in the fan motor. Needs to be replaced or [greased up](https://www.youtube.com/watch?v=Z9_jIa2WADc)

**Comment by lindskogen** [comment]
:cry:

**Comment by abjugard** [comment]
Rest in RIP ligga :cry:

**Comment by Tejpbit** [comment]
I've greased it up once more. But wouldn't get my hopes up... It didn't run as smooth as last time when @Edholm helped me. But atleast it doesn't squeel anymore. Issue closed for now...
