### ISSUE TITLE
Missing taggin of kitchen drawers

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#81]
The previously tags: FORKS, KNIVES, SPOONS, etc. are now missing from the kitchen drawers. This will result in disaster regarding the cutlery not finding it's way into any drawers. If it's easy to keep the kitchen tidy it will tend to be less messy.

**Comment by ghost** [comment]
Perfect issue for the städnollan to attend to 💪

**Comment by vidare** [comment]
What I know there is no städnolla nor could this fall under their responsibility.

**Comment by ericlp** [comment]
This seems to be solved.
