### ISSUE TITLE
Studierum - New furniture arrangment

### ISSUE THREAD

**Issue by vidare** [cthit/Hubben#82]
The new furnishing, or rather the rearrangement of the existing one is leaving much to be desired. Hopefully this is only a remnant from when the floor was waxed. Although appearing more "roomy" the actual space for sitting has been reduced and proven impractical for persons of above average length.

There is a reason for the old arrangement, it works and is the most efficient given the size of the room and that the sofa is a dominant part of it. As it is now you have to literally climb over chairs to get to all seats and this will only get more problematic when the room get crowded.

**Comment by Xiaoming94** [comment]
A better solution: get Rid of Cetac and break that wall for a single big study room 😁

**Comment by vidare** [comment]
That would be a long term target and a different issue altogether. As of now, reverting to the previously furniture configuration would restore the lost seats.
