### ISSUE TITLE
Rules regarding when to make new coffee 

### ISSUE THREAD

**Issue by Holmus** [cthit/Hubben#9]
Due to the fact most people are stupid or atleast when it comes to coffee seem to ignore their moral values we need a clear rule-set to define when I as an IT student should make more coffee.

**NOTE** these rules especially apply to Guran, due to incidents occurring in previous exam weeks.

My suggestion for this rule-set would be as follows:

- One must always leave atleast 1 cup or brew new coffee.

F.e if there are 1.5 cups left and I take 0.75 cups, the remainder in the coffee pot will be 0.75 cups, which is not allowed. The solution is either taking 0.5 cups for myself thus leaving 1 cup or start brewing more coffee.

Other solution, the so called "städnollan" makes sure coffee production keeps up with coffee consumption. In case this is not possible, "städnollan" should provide Power King to ensure Caffeine levels are up to coding standards.

**Comment by Dr-Horv** [comment]
I agree with the rule. We should have an informative sign who explains this to less experienced coffee-drinkers.

**Comment by lindskogen** [comment]
:coffee: :coffee: :coffee:
